### ISSUE TITLE
Different order of operations inside resnet forwards compared with original

### ISSUE THREAD

**Issue by Rimest** [zhaoweicai/EdMIPS#4]
Why is there different order of operations inside resnet forwards compared with original?

**Comment by Rimest** [comment]
Yours: https://github.com/zhaoweicai/EdMIPS/blob/master/models/mixresnet.py#L144-L146
Original: https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L232-L235

**Comment by zhaoweicai** [comment]
This can be traced back to the very early XNOR-Net, https://arxiv.org/pdf/1603.05279.pdf. If you don't change the layer order, the results will be worse.

**Comment by Rimest** [comment]
Thank you very much for the response!
