### ISSUE TITLE
Why do we need asserts for resnet and this part?

### ISSUE THREAD

**Issue by diff7** [zhaoweicai/EdMIPS#6]
Hi, thank you for a nice work, I was wondering, why do we need assertions at this part?

https://github.com/zhaoweicai/EdMIPS/blob/690a7c650ea468f8e9273aceb833f1849f980ff9/models/mixresnet.py#L154

Also, why did not you use nn.AdaptiveAvgPool2d((1, 1))  instead of nn.AvgPool2d(7) for resnets?

Thank you!

**Comment by zhaoweicai** [comment]
This is because we used a single main function to support different architectures. For example, inception uses larger image as input. We didn't want to mistakenly froward the larger image inputs into the resnet, so we added this assertion.
